title:  BG
tabtitle:  Bijay Gurung
tagline:  Learning

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-bglearning-github-io'

google-ID: 'UA-111877750-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Things-Of-Note', url: 'bglearning.substack.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'medium', link: 'https://medium.com/@bijaygurung'}
- {icon: 'github', link: 'https://www.github.com/bglearning'}
- {icon: 'quora', link: 'https://www.quora.com/profile/Bijay-Gurung-5'}
- {icon: 'twitter', link: 'https://twitter.com/bg_learning'}
- {icon: 'facebook', link: 'https://www.facebook.com/bijay.gurung.37454'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/bijay-gurung/'}
